plugins {
    id 'org.springframework.boot' version '3.4.4'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'java'
    id 'jacoco'
}

sourceCompatibility = '21'
targetCompatibility = '21'
group = 'com.rhels.demo'

repositories {
    mavenCentral()
}
dependencies {
    implementation 'org.apache.logging.log4j:log4j-api:3.0.0-beta2'
    implementation 'org.apache.logging.log4j:log4j-to-slf4j:3.0.0-beta2'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'

    // https://docs.spring.io/spring-boot/docs/2.6.4/reference/html/features.html#features.testing
    // imports both spring-boot-test, spring-boot-test-autoconfigure test modules as well has JUnit, AssertJ, Hamcrest and a number of other useful libraries.
    // JUnit: The de-facto standard for unit testing Java applications.
    // Spring Test & Spring Boot Test: Utilities and integration test support for Spring Boot applications.
    // AssertJ: A fluent assertion library.
    // Hamcrest: A librar y of matcher objects (also known as constraints or predicates).
    // Mockito: Java mocking framework.
    // JSONassert: An assertion library for JSON.
    // JsonPath: XPath for JSON.
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

test {
    useJUnitPlatform()
}